export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_OK = "PURCHASE_BURGER_OK";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_OK = "FETCH_ORDERS_OK";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_OK = "DELETE_ORDER_OK";
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED";

export const AUTHENTICATE_START = "AUTHENTICATE_START";
export const AUTHENTICATE_OK = "AUTHENTICATE_OK";
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED";
export const AUTHENTICATE_LOGOUT = "AUTHENTICATE_LOGOUT";
